### ISSUE TITLE
Noetic Python 2 dependency on qt5 opengl bindings

### ISSUE THREAD

**Issue by sloretz** [ros-visualization/gl_dependency#1]
It looks like the [noetic source entry for `gl_dependency`](https://github.com/ros/rosdistro/blob/1b96f7c4f230e878f9901a6cc3465af9cbca22fc/noetic/distribution.yaml#L134-L139) depends on the Python 2 rosdep key `python-qt5-bindings-gl`.

https://github.com/ros-visualization/gl_dependency/blob/a08a0277f7de6481b75493890b63795a2e2f8293/package.xml#L11

Maybe it should use the [rosdep key `python3-qt5-bindings-gl`](https://github.com/ros/rosdistro/blob/1b96f7c4f230e878f9901a6cc3465af9cbca22fc/rosdep/python.yaml#L5302-L5306) instead?

**Comment by dirk-thomas** [comment]
This packages has not been updated for Noetic / Python 3 yet. Yes, it will need a conditional dependency for that.
